### PR TITLE
Add valid field for Formik input

### PR DESCRIPTION
**Pull request by hututudor**
Jira: https://etvas.atlassian.net/browse/ETK-28

* add valid prop on Formik wrapper

### CODE REVIEW

**Review by alsofronie — COMMENTED** [review]
What about valid (the one with the green checkbox)? That would appear if no error/warning and touched true.

**Comment by hututudor** [comment]
> What about valid (the one with the green checkbox)? That would appear if no error/warning and touched true.

That's exactly what I did. I added the valid prop for when the input is valid

**Comment by hututudor** [comment]
> > What about valid (the one with the green checkbox)? That would appear if no error/warning and touched true.
> 
> That's exactly what I did. I added the valid prop for when the input is valid

If the field is empty, there should be a validation error on it. If there is no validation, it means that an empty input is valid.

**Comment by alsofronie** [comment]
A field with no validation attached will have a gray check icon, always.
A field with validation attached will have a grey check if not touched and corresponding coloured icon if touched.

That means an empty field with "required" validation will have a grey check until you touch it, the icon will change to error when focused and change again to green check when I input something in it.

**Review by alsofronie — APPROVED** [review]

**Pull request merged**
